--- #YAML:1.0
name:               Music-Canon
version:            0.12
abstract:           routines for musical canon construction
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    List::Util:           0
    Music::AtonalUtil:    0.7
    Music::LilyPondUtil:  0.43
    Music::Scales:        0.07
    Test::Exception:      0
    Test::More:           0
resources:
    homepage:    http://github.com/thrig/Music-Canon
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/thrig/Music-Canon
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
